/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.ScheduleCheck;
import Controller.ScheduleCreation;
import Controller.Singleton;
import DataModel.Course;
import java.util.ArrayList;

/**
 * JPanel to allow user to add courses to a profile. 
 * @author SusiManning
 */
public class AddClasses extends javax.swing.JPanel {
    
    //Create instances of necessary classes
    Course course = new Course();
    ScheduleCreation sched = new ScheduleCreation();
    ScheduleCheck schedCheck = new ScheduleCheck();
    Singleton values = Singleton.getInstance();
    /**
     * Creates new form AddClasses
     */
    public AddClasses() {
        initComponents();
        
        classAOutput.setEditable(false);
        classBOutput.setEditable(false);
        classCOutput.setEditable(false);
        classDOutput.setEditable(false);
        classEOutput.setEditable(false);
        classFOutput.setEditable(false);
        classGOutput.setEditable(false);
        classHOutput.setEditable(false);
        
        info.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        building = new javax.swing.JComboBox<>();
        startHour = new javax.swing.JComboBox<>();
        startMinute = new javax.swing.JComboBox<>();
        endHour = new javax.swing.JComboBox<>();
        endMinute = new javax.swing.JComboBox<>();
        addClassButton = new javax.swing.JButton();
        buildingLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        classDays = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        ampmStart = new javax.swing.JComboBox<>();
        ampmEnd = new javax.swing.JComboBox<>();
        classCOutput = new javax.swing.JTextField();
        classAOutput = new javax.swing.JTextField();
        classDOutput = new javax.swing.JTextField();
        classFOutput = new javax.swing.JTextField();
        classEOutput = new javax.swing.JTextField();
        classBOutput = new javax.swing.JTextField();
        classGOutput = new javax.swing.JTextField();
        classHOutput = new javax.swing.JTextField();
        removeButtonA = new javax.swing.JButton();
        removeButtonE = new javax.swing.JButton();
        removeButtonD = new javax.swing.JButton();
        removeButtonH = new javax.swing.JButton();
        removeButtonC = new javax.swing.JButton();
        removeButtonB = new javax.swing.JButton();
        removeButtonF = new javax.swing.JButton();
        removeButtonG = new javax.swing.JButton();
        populateClasses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        info = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(0, 255, 0));

        building.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BAB", "CCH", "CGV", "CRH", "CTC", "ENG", "FFH", "LIB", "MOR", "MSB", "NCH", "NUR", "OKT", "OPB", "ROB", "SCH", "SKH", "SPR", "SSB", "SST", "SWI", "UFC", "VBC", "WIL" }));

        startHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        startHour.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                startHourPopupMenuWillBecomeVisible(evt);
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        startMinute.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55" }));

        endHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        endMinute.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55" }));

        addClassButton.setText("Add Class");
        addClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClassButtonActionPerformed(evt);
            }
        });

        buildingLabel.setText("Building:");

        jLabel2.setText("Class Start:");

        jLabel3.setText("Class End:");

        jLabel4.setText(":");

        jLabel1.setText(":");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel11.setText("Class Schedule");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel12.setText("Add Classes");

        jButton1.setText("View Map");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        classDays.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MW", "TTh", "MWF", "MTWF", "S" }));

        jLabel5.setText("Days:");

        ampmStart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));

        ampmEnd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));

        classGOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classGOutputActionPerformed(evt);
            }
        });

        removeButtonA.setText("X");
        removeButtonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonAActionPerformed(evt);
            }
        });

        removeButtonE.setText("X");
        removeButtonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonEActionPerformed(evt);
            }
        });

        removeButtonD.setText("X");
        removeButtonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonDActionPerformed(evt);
            }
        });

        removeButtonH.setText("X");
        removeButtonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonHActionPerformed(evt);
            }
        });

        removeButtonC.setText("X");
        removeButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonCActionPerformed(evt);
            }
        });

        removeButtonB.setText("X");
        removeButtonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonBActionPerformed(evt);
            }
        });

        removeButtonF.setText("X");
        removeButtonF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonFActionPerformed(evt);
            }
        });

        removeButtonG.setText("X");
        removeButtonG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonGActionPerformed(evt);
            }
        });

        populateClasses.setText("Populate Classes");
        populateClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                populateClassesActionPerformed(evt);
            }
        });

        info.setColumns(10);
        info.setRows(3);
        info.setText("Click \"Populate Classes\" first \nto populate fields with already \nsaved classes.");
        jScrollPane1.setViewportView(info);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buildingLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(building, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addClassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(populateClasses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(classDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(endHour, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(endMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ampmEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(startHour, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(startMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ampmStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(classDOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classBOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classAOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classCOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(removeButtonD, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(removeButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(removeButtonA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeButtonB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(classEOutput)
                        .addComponent(classFOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                    .addComponent(classGOutput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classHOutput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(removeButtonG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(removeButtonE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeButtonH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(removeButtonF, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(building, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buildingLabel)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(ampmStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(endHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jButton1)
                            .addComponent(ampmEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(populateClasses))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(classDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addComponent(addClassButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(classAOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(classEOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeButtonA)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(15, 15, 15)
                        .addComponent(removeButtonE, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classFOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classBOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeButtonB)
                    .addComponent(removeButtonF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classCOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classGOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeButtonC)
                    .addComponent(removeButtonG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classDOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classHOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeButtonD)
                    .addComponent(removeButtonH))
                .addGap(111, 111, 111))
        );
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Unused method.
     * @param evt 
     */
    private void startHourPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_startHourPopupMenuWillBecomeVisible
        // TODO add your handling code here:
    }//GEN-LAST:event_startHourPopupMenuWillBecomeVisible
    /**
     * Unused method.
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Map().setVisible(true); //Displays Map.java on the screen so the user can see the map 
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * Button to save entered information from GUI into the user's profile and 
     * into the classes data table.
     * @param evt 
     */
    private void addClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClassButtonActionPerformed
        //Set variables for inputs from GUI
        String b = null;
        String sHour = null;
        String sMin = null;
        String eHour = null;
        String eMin = null;
        String timeStart = null;
        String timeEnd = null;
        String days = null;
        
        //Save inputs from GUI as strings
        b = (String)building.getSelectedItem();
        sHour = (String)startHour.getSelectedItem();
        sMin = (String)startMinute.getSelectedItem();
        eHour = (String)endHour.getSelectedItem();
        eMin = (String)endMinute.getSelectedItem();
        days = (String)classDays.getSelectedItem();
        timeStart = (String)ampmStart.getSelectedItem();
        timeEnd = (String)ampmEnd.getSelectedItem();
        
        //Save necessary variables into course object
        course.setCourseTime((sHour+":"+sMin+timeStart));
        course.setCourseLocation(b);
        course.setCourseDays(days);
        
        //Check for empty field
        if(classAOutput.getText().isEmpty()){
            classAOutput.setText(b + " " + sHour+":"+sMin+timeStart + " " + days);
        }else if(classBOutput.getText().isEmpty()){
           classBOutput.setText(b + " " + sHour+":"+sMin+timeStart + " " + days); 
        }else if(classCOutput.getText().isEmpty()){
           classCOutput.setText(b + " " + sHour+":"+sMin+timeStart + " " + days); 
        }else if(classDOutput.getText().isEmpty()){
           classDOutput.setText(b + " " + sHour+":"+sMin+timeStart + " " + days); 
        }else if(classEOutput.getText().isEmpty()){
           classEOutput.setText(b + " " + sHour+":"+sMin+timeStart + " " + days); 
        }else if(classFOutput.getText().isEmpty()){
           classFOutput.setText(b + " " + sHour+":"+sMin+timeStart + " " + days); 
        }else if(classGOutput.getText().isEmpty()){
           classGOutput.setText(b + " " + sHour+":"+sMin+timeStart + " " + days); 
        }else if(classHOutput.getText().isEmpty()){
           classHOutput.setText(b + " " + sHour+":"+sMin+timeStart + " " + days); 
        }else
            System.out.print("Classes are full.");
        
        //Add course to database
        sched.addCourse(course);
        
        //Get course ID
        int class_id = schedCheck.checkClass(course);

        //Need to get user's id to call sched.addStudentCourse().
        sched.addStudentCourse(values.profid, class_id);
    }//GEN-LAST:event_addClassButtonActionPerformed
    /**
     * Unused method.
     * @param evt 
     */
    private void classGOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classGOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classGOutputActionPerformed
    /**
     * Empty the field
     * @param evt 
     */
    private void removeButtonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonAActionPerformed
        classAOutput.setText("");
    }//GEN-LAST:event_removeButtonAActionPerformed
    /**
     * Empty the field
     * @param evt 
     */
    private void removeButtonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonBActionPerformed
        classBOutput.setText("");
    }//GEN-LAST:event_removeButtonBActionPerformed
    /**
     * Empty the field
     * @param evt 
     */
    private void removeButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonCActionPerformed
        classCOutput.setText("");
    }//GEN-LAST:event_removeButtonCActionPerformed
    /**
     * Empty the field
     * @param evt 
     */
    private void removeButtonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonDActionPerformed
        classDOutput.setText("");
    }//GEN-LAST:event_removeButtonDActionPerformed
    /**
     * Empty the field
     * @param evt 
     */
    private void removeButtonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonEActionPerformed
        classEOutput.setText("");
    }//GEN-LAST:event_removeButtonEActionPerformed
    /**
     * Empty the field
     * @param evt 
     */
    private void removeButtonFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonFActionPerformed
        classFOutput.setText("");
    }//GEN-LAST:event_removeButtonFActionPerformed
    /**
     * Empty the field
     * @param evt 
     */
    private void removeButtonGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonGActionPerformed
        classGOutput.setText("");
    }//GEN-LAST:event_removeButtonGActionPerformed
    /**
     * Empty the field
     * @param evt 
     */
    private void removeButtonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonHActionPerformed
        classHOutput.setText("");
    }//GEN-LAST:event_removeButtonHActionPerformed
    /**
     * Button to populate fields with the user's saved classes. Uses to singleton
     * to get the schedule and classes of the user.
     * @param evt 
     */
    private void populateClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_populateClassesActionPerformed
        ArrayList <Course> classArray = schedCheck.getSchedule(values.profid);
        // Loop through elements.
        for (Course c : classArray){
            String place = c.getCourseLocation();
            String time = c.getCourseTime();
            String days = c.getCourseDays();
            String total = place+ " " + time + " " + days;
            
            if(classAOutput.getText().isEmpty()){
                classAOutput.setText(total);
            }else if(classBOutput.getText().isEmpty()){
               classBOutput.setText(total); 
            }else if(classCOutput.getText().isEmpty()){
               classCOutput.setText(total); 
            }else if(classDOutput.getText().isEmpty()){
               classDOutput.setText(total); 
            }else if(classEOutput.getText().isEmpty()){
               classEOutput.setText(total); 
            }else if(classFOutput.getText().isEmpty()){
               classFOutput.setText(total); 
            }else if(classGOutput.getText().isEmpty()){
               classGOutput.setText(total); 
            }else{
               classHOutput.setText(total); 
            }
            
        }
    }//GEN-LAST:event_populateClassesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClassButton;
    private javax.swing.JComboBox<String> ampmEnd;
    private javax.swing.JComboBox<String> ampmStart;
    private javax.swing.JComboBox<String> building;
    private javax.swing.JLabel buildingLabel;
    private javax.swing.JTextField classAOutput;
    private javax.swing.JTextField classBOutput;
    private javax.swing.JTextField classCOutput;
    private javax.swing.JTextField classDOutput;
    private javax.swing.JComboBox<String> classDays;
    private javax.swing.JTextField classEOutput;
    private javax.swing.JTextField classFOutput;
    private javax.swing.JTextField classGOutput;
    private javax.swing.JTextField classHOutput;
    private javax.swing.JComboBox<String> endHour;
    private javax.swing.JComboBox<String> endMinute;
    private javax.swing.JTextArea info;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton populateClasses;
    private javax.swing.JButton removeButtonA;
    private javax.swing.JButton removeButtonB;
    private javax.swing.JButton removeButtonC;
    private javax.swing.JButton removeButtonD;
    private javax.swing.JButton removeButtonE;
    private javax.swing.JButton removeButtonF;
    private javax.swing.JButton removeButtonG;
    private javax.swing.JButton removeButtonH;
    private javax.swing.JComboBox<String> startHour;
    private javax.swing.JComboBox<String> startMinute;
    // End of variables declaration//GEN-END:variables
}
