/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
/**
 *
 * @author SusiManning
 */
public class gui2 extends javax.swing.JFrame {

    /**
     * Creates new form gui2
     */
    public gui2() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parentPanel = new javax.swing.JPanel();
        login1 = new GUI.Login();
        info1 = new GUI.Info();
        addClasses1 = new GUI.AddClasses();
        ride1 = new GUI.Ride();
        buttonPanel = new javax.swing.JPanel();
        loginButtons = new javax.swing.JPanel();
        createAccount = new javax.swing.JButton();
        letsRideButton = new javax.swing.JButton();
        editAccount = new javax.swing.JButton();
        matchButtons = new javax.swing.JPanel();
        editAccountButton = new javax.swing.JButton();
        matchRideButton = new javax.swing.JButton();
        accountButtons = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        addClassButton = new javax.swing.JButton();
        addClassesButtons = new javax.swing.JPanel();
        addClassButton2 = new javax.swing.JButton();
        findRideButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        parentPanel.setLayout(new java.awt.CardLayout());
        parentPanel.add(login1, "card6");
        parentPanel.add(info1, "card6");
        parentPanel.add(addClasses1, "card6");
        parentPanel.add(ride1, "card6");

        buttonPanel.setBackground(new java.awt.Color(0, 0, 0));
        buttonPanel.setLayout(new java.awt.CardLayout());

        loginButtons.setBackground(new java.awt.Color(0, 0, 0));

        createAccount.setText("Create Account");
        createAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountActionPerformed(evt);
            }
        });

        letsRideButton.setText("Find a Ride");
        letsRideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letsRideButtonActionPerformed(evt);
            }
        });

        editAccount.setText("Edit Account");
        editAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginButtonsLayout = new javax.swing.GroupLayout(loginButtons);
        loginButtons.setLayout(loginButtonsLayout);
        loginButtonsLayout.setHorizontalGroup(
            loginButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(letsRideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(createAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        loginButtonsLayout.setVerticalGroup(
            loginButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginButtonsLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(loginButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editAccount)
                    .addComponent(letsRideButton)
                    .addComponent(createAccount))
                .addContainerGap())
        );

        buttonPanel.add(loginButtons, "card6");

        matchButtons.setBackground(new java.awt.Color(0, 0, 0));

        editAccountButton.setText("Edit Account");
        editAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAccountButtonActionPerformed(evt);
            }
        });

        matchRideButton.setText("Find a Ride!");
        matchRideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matchRideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout matchButtonsLayout = new javax.swing.GroupLayout(matchButtons);
        matchButtons.setLayout(matchButtonsLayout);
        matchButtonsLayout.setHorizontalGroup(
            matchButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(matchButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(matchRideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        matchButtonsLayout.setVerticalGroup(
            matchButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(matchButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(matchButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editAccountButton)
                    .addComponent(matchRideButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonPanel.add(matchButtons, "card6");

        accountButtons.setBackground(new java.awt.Color(0, 0, 0));

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Find A Ride");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        addClassButton.setText("Add Class");
        addClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClassButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accountButtonsLayout = new javax.swing.GroupLayout(accountButtons);
        accountButtons.setLayout(accountButtonsLayout);
        accountButtonsLayout.setHorizontalGroup(
            accountButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addClassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        accountButtonsLayout.setVerticalGroup(
            accountButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accountButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addClassButton)
                    .addComponent(cancelButton)
                    .addComponent(saveButton))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        buttonPanel.add(accountButtons, "card7");

        addClassesButtons.setBackground(new java.awt.Color(0, 0, 0));

        addClassButton2.setText("Add Class");

        findRideButton.setText("Find a Ride!");
        findRideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findRideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addClassesButtonsLayout = new javax.swing.GroupLayout(addClassesButtons);
        addClassesButtons.setLayout(addClassesButtonsLayout);
        addClassesButtonsLayout.setHorizontalGroup(
            addClassesButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addClassesButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addClassButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(findRideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        addClassesButtonsLayout.setVerticalGroup(
            addClassesButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addClassesButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addClassesButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addClassButton2)
                    .addComponent(findRideButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonPanel.add(addClassesButtons, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(parentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 399, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        parentPanel.removeAll();
        parentPanel.add(login1);
        parentPanel.repaint();
        parentPanel.revalidate();
        
        buttonPanel.removeAll();
        buttonPanel.add(loginButtons);
        buttonPanel.repaint();
        buttonPanel.revalidate(); 
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        parentPanel.removeAll();
        parentPanel.add(ride1);
        parentPanel.repaint();
        parentPanel.revalidate();
        
        buttonPanel.removeAll();
        buttonPanel.add(matchButtons);
        buttonPanel.repaint();
        buttonPanel.revalidate(); 
    }//GEN-LAST:event_saveButtonActionPerformed

    private void addClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClassButtonActionPerformed
        parentPanel.removeAll();
        parentPanel.add(addClasses1);
        parentPanel.repaint();
        parentPanel.revalidate(); 
        
        buttonPanel.removeAll();
        buttonPanel.add(addClassesButtons);
        buttonPanel.repaint();
        buttonPanel.revalidate();
    }//GEN-LAST:event_addClassButtonActionPerformed

    private void findRideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findRideButtonActionPerformed
        parentPanel.removeAll();
        parentPanel.add(ride1);
        parentPanel.repaint();
        parentPanel.revalidate(); 
        
        buttonPanel.removeAll();
        buttonPanel.add(matchButtons);
        buttonPanel.repaint();
        buttonPanel.revalidate();
    }//GEN-LAST:event_findRideButtonActionPerformed

    private void letsRideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letsRideButtonActionPerformed
        parentPanel.removeAll();
        parentPanel.add(ride1);
        parentPanel.repaint();
        parentPanel.revalidate(); 
        
        buttonPanel.removeAll();
        buttonPanel.add(matchButtons);
        buttonPanel.repaint();
        buttonPanel.revalidate();
    }//GEN-LAST:event_letsRideButtonActionPerformed

    private void editAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAccountActionPerformed
        parentPanel.removeAll();
        parentPanel.add(info1);
        parentPanel.repaint();
        parentPanel.revalidate(); 
        
        buttonPanel.removeAll();
        buttonPanel.add(accountButtons);
        buttonPanel.repaint();
        buttonPanel.revalidate(); 
    }//GEN-LAST:event_editAccountActionPerformed

    private void createAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountActionPerformed
        parentPanel.removeAll();
        parentPanel.add(info1);
        parentPanel.repaint();
        parentPanel.revalidate(); 
        
        buttonPanel.removeAll();
        buttonPanel.add(accountButtons);
        buttonPanel.repaint();
        buttonPanel.revalidate();
    }//GEN-LAST:event_createAccountActionPerformed

    private void editAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAccountButtonActionPerformed
        parentPanel.removeAll();
        parentPanel.add(info1);
        parentPanel.repaint();
        parentPanel.revalidate(); 

        buttonPanel.removeAll();
        buttonPanel.add(accountButtons);
        buttonPanel.repaint();
        buttonPanel.revalidate(); 
    }//GEN-LAST:event_editAccountButtonActionPerformed

    private void matchRideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matchRideButtonActionPerformed
        parentPanel.removeAll();
        parentPanel.add(ride1);
        parentPanel.repaint();
        parentPanel.revalidate(); 
        
        buttonPanel.removeAll();
        buttonPanel.add(matchButtons);
        buttonPanel.repaint();
        buttonPanel.revalidate();
    }//GEN-LAST:event_matchRideButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accountButtons;
    private javax.swing.JButton addClassButton;
    private javax.swing.JButton addClassButton2;
    private GUI.AddClasses addClasses1;
    private javax.swing.JPanel addClassesButtons;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createAccount;
    private javax.swing.JButton editAccount;
    private javax.swing.JButton editAccountButton;
    private javax.swing.JButton findRideButton;
    private GUI.Info info1;
    private javax.swing.JButton letsRideButton;
    private GUI.Login login1;
    private javax.swing.JPanel loginButtons;
    private javax.swing.JPanel matchButtons;
    private javax.swing.JButton matchRideButton;
    private javax.swing.JPanel parentPanel;
    private GUI.Ride ride1;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
