/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
/**
 *
 * @author SusiManning
 */
public class gui2 extends javax.swing.JFrame {

    Login loginCreds = new Login();
    /**
     * Creates new form gui2
     */
    public gui2() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parentPanel = new javax.swing.JPanel();
        login1 = new GUI.Login();
        ride1 = new GUI.Ride();
        info1 = new GUI.Info();
        buttonPanel = new javax.swing.JPanel();
        loginButtons = new javax.swing.JSplitPane();
        loginButtons2 = new javax.swing.JSplitPane();
        letsRideButton = new javax.swing.JButton();
        createAccount = new javax.swing.JButton();
        editAccount = new javax.swing.JButton();
        matchButtons = new javax.swing.JSplitPane();
        editAccountButton = new javax.swing.JButton();
        matchRideButton = new javax.swing.JButton();
        accountButtons = new javax.swing.JSplitPane();
        accountButtons2 = new javax.swing.JSplitPane();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        addClassButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        parentPanel.setLayout(new java.awt.CardLayout());
        parentPanel.add(login1, "card4");
        parentPanel.add(ride1, "card4");
        parentPanel.add(info1, "card3");

        buttonPanel.setBackground(new java.awt.Color(0, 0, 0));
        buttonPanel.setLayout(new java.awt.CardLayout());

        loginButtons.setBackground(new java.awt.Color(0, 0, 0));

        letsRideButton.setText("Let's Ride!");
        letsRideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letsRideButtonActionPerformed(evt);
            }
        });
        loginButtons2.setLeftComponent(letsRideButton);

        createAccount.setText("Go");
        loginButtons2.setRightComponent(createAccount);

        loginButtons.setRightComponent(loginButtons2);

        editAccount.setText("Edit Account");
        editAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAccountActionPerformed(evt);
            }
        });
        loginButtons.setLeftComponent(editAccount);

        buttonPanel.add(loginButtons, "card4");

        matchButtons.setBackground(new java.awt.Color(0, 0, 0));

        editAccountButton.setText("Edit my Account");
        editAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAccountButtonActionPerformed(evt);
            }
        });
        matchButtons.setLeftComponent(editAccountButton);

        matchRideButton.setText("Find My Ride!");
        matchButtons.setRightComponent(matchRideButton);

        buttonPanel.add(matchButtons, "card3");

        accountButtons.setBackground(new java.awt.Color(0, 0, 0));

        accountButtons2.setBackground(new java.awt.Color(0, 0, 0));

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        accountButtons2.setLeftComponent(cancelButton);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        accountButtons2.setRightComponent(saveButton);

        accountButtons.setRightComponent(accountButtons2);

        addClassButton.setText("Add Class");
        accountButtons.setLeftComponent(addClassButton);

        buttonPanel.add(accountButtons, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(parentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void letsRideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letsRideButtonActionPerformed
        parentPanel.removeAll();
        parentPanel.add(ride1);
        parentPanel.repaint();
        parentPanel.revalidate();
        
        buttonPanel.removeAll();
        buttonPanel.add(matchButtons);
        parentPanel.repaint();
        parentPanel.revalidate(); 
    }//GEN-LAST:event_letsRideButtonActionPerformed

    private void editAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAccountButtonActionPerformed
        parentPanel.removeAll();
        parentPanel.add(info1);
        parentPanel.repaint();
        parentPanel.revalidate(); 
        
        buttonPanel.removeAll();
        buttonPanel.add(accountButtons);
        parentPanel.repaint();
        parentPanel.revalidate(); 
    }//GEN-LAST:event_editAccountButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        parentPanel.removeAll();
        parentPanel.add(login1);
        parentPanel.repaint();
        parentPanel.revalidate();
        
        buttonPanel.removeAll();
        buttonPanel.add(loginButtons);
        parentPanel.repaint();
        parentPanel.revalidate(); 
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        parentPanel.removeAll();
        parentPanel.add(ride1);
        parentPanel.repaint();
        parentPanel.revalidate();
        
        buttonPanel.removeAll();
        buttonPanel.add(matchButtons);
        parentPanel.repaint();
        parentPanel.revalidate(); 
    }//GEN-LAST:event_saveButtonActionPerformed

    private void editAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAccountActionPerformed
        parentPanel.removeAll();
        parentPanel.add(info1);
        parentPanel.repaint();
        parentPanel.revalidate(); 
        
        buttonPanel.removeAll();
        buttonPanel.add(accountButtons);
        parentPanel.repaint();
        parentPanel.revalidate(); 
    }//GEN-LAST:event_editAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane accountButtons;
    private javax.swing.JSplitPane accountButtons2;
    private javax.swing.JButton addClassButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createAccount;
    private javax.swing.JButton editAccount;
    private javax.swing.JButton editAccountButton;
    private GUI.Info info1;
    private javax.swing.JButton letsRideButton;
    private GUI.Login login1;
    private javax.swing.JSplitPane loginButtons;
    private javax.swing.JSplitPane loginButtons2;
    private javax.swing.JSplitPane matchButtons;
    private javax.swing.JButton matchRideButton;
    private javax.swing.JPanel parentPanel;
    private GUI.Ride ride1;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
