/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

//import GUI.Info;

import Controller.ScheduleCheck;
import Controller.Singleton;
import DataModel.Course;
import java.util.ArrayList;
import DataModel.Profile;
import java.awt.Color;


/**
 *
 * @author elizadellert
 */
public class Ride extends javax.swing.JPanel {
    
     /**
     * Method that creates the GUI for the reserve ride screen.
     */

    ScheduleCheck schedCheck = new ScheduleCheck();
    Singleton values = Singleton.getInstance();
    
    public Ride() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        from1 = new javax.swing.JTextField();
        to1 = new javax.swing.JTextField();
        from2 = new javax.swing.JTextField();
        to2 = new javax.swing.JTextField();
        to3 = new javax.swing.JTextField();
        from3 = new javax.swing.JTextField();
        from4 = new javax.swing.JTextField();
        to5 = new javax.swing.JTextField();
        to4 = new javax.swing.JTextField();
        to7 = new javax.swing.JTextField();
        to6 = new javax.swing.JTextField();
        to8 = new javax.swing.JTextField();
        from7 = new javax.swing.JTextField();
        from8 = new javax.swing.JTextField();
        from6 = new javax.swing.JTextField();
        from5 = new javax.swing.JTextField();
        chooseFrom1 = new javax.swing.JButton();
        chooseTo1 = new javax.swing.JButton();
        chooseFrom2 = new javax.swing.JButton();
        chooseFrom3 = new javax.swing.JButton();
        chooseFrom4 = new javax.swing.JButton();
        chooseFrom5 = new javax.swing.JButton();
        chooseFrom6 = new javax.swing.JButton();
        chooseFrom7 = new javax.swing.JButton();
        chooseFrom8 = new javax.swing.JButton();
        chooseTo2 = new javax.swing.JButton();
        chooseTo3 = new javax.swing.JButton();
        chooseTo4 = new javax.swing.JButton();
        chooseTo7 = new javax.swing.JButton();
        chooseTo8 = new javax.swing.JButton();
        chooseTo5 = new javax.swing.JButton();
        chooseTo6 = new javax.swing.JButton();
        option1 = new javax.swing.JTextField();
        option4 = new javax.swing.JTextField();
        option2 = new javax.swing.JTextField();
        option3 = new javax.swing.JTextField();
        populateButton = new javax.swing.JButton();
        matchButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 255, 0));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("From");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("To");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Options");

        from4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                from4ActionPerformed(evt);
            }
        });

        to6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                to6ActionPerformed(evt);
            }
        });

        from7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                from7ActionPerformed(evt);
            }
        });

        from8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                from8ActionPerformed(evt);
            }
        });

        chooseFrom1.setText("O");
        chooseFrom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFrom1ActionPerformed(evt);
            }
        });

        chooseTo1.setText("O");
        chooseTo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseTo1ActionPerformed(evt);
            }
        });

        chooseFrom2.setText("O");
        chooseFrom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFrom2ActionPerformed(evt);
            }
        });

        chooseFrom3.setText("O");
        chooseFrom3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFrom3ActionPerformed(evt);
            }
        });

        chooseFrom4.setText("O");
        chooseFrom4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFrom4ActionPerformed(evt);
            }
        });

        chooseFrom5.setText("O");
        chooseFrom5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFrom5ActionPerformed(evt);
            }
        });

        chooseFrom6.setText("O");
        chooseFrom6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFrom6ActionPerformed(evt);
            }
        });

        chooseFrom7.setText("O");
        chooseFrom7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFrom7ActionPerformed(evt);
            }
        });

        chooseFrom8.setText("O");
        chooseFrom8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFrom8ActionPerformed(evt);
            }
        });

        chooseTo2.setText("O");
        chooseTo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseTo2ActionPerformed(evt);
            }
        });

        chooseTo3.setText("O");
        chooseTo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseTo3ActionPerformed(evt);
            }
        });

        chooseTo4.setText("O");
        chooseTo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseTo4ActionPerformed(evt);
            }
        });

        chooseTo7.setText("O");
        chooseTo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseTo7ActionPerformed(evt);
            }
        });

        chooseTo8.setText("O");
        chooseTo8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseTo8ActionPerformed(evt);
            }
        });

        chooseTo5.setText("O");
        chooseTo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseTo5ActionPerformed(evt);
            }
        });

        chooseTo6.setText("O");
        chooseTo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseTo6ActionPerformed(evt);
            }
        });

        populateButton.setText("Populate");
        populateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                populateButtonActionPerformed(evt);
            }
        });

        matchButton.setText("Match");
        matchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(populateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(71, 71, 71))
                                .addComponent(from1)
                                .addComponent(from2)
                                .addComponent(from3)
                                .addComponent(from5)
                                .addComponent(from4)
                                .addComponent(from6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(chooseFrom6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chooseFrom4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chooseFrom3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chooseFrom2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chooseFrom1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(chooseFrom5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(from7, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                .addComponent(from8))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(chooseFrom8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chooseFrom7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(to7, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(to6)
                            .addComponent(to8)
                            .addComponent(to5)
                            .addComponent(to4)
                            .addComponent(to3)
                            .addComponent(to2)
                            .addComponent(to1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chooseTo1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chooseTo2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chooseTo7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chooseTo8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chooseTo6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chooseTo5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chooseTo3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 37, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(option1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(12, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(option3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(option4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(option2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chooseTo4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(matchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(from1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(to1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chooseTo1)
                            .addComponent(chooseFrom1))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(from2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chooseFrom2)
                            .addComponent(to2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chooseTo2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(from3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chooseFrom3)
                            .addComponent(to3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chooseTo3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(option1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(option2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(to4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chooseTo4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(to5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chooseTo5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(option3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chooseFrom6)
                            .addComponent(to6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chooseTo6)
                            .addComponent(from6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(from7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chooseFrom7)
                            .addComponent(chooseTo7)
                            .addComponent(to7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(option4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chooseFrom4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(from4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(from5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chooseFrom5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(from8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseFrom8)
                    .addComponent(to8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseTo8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(populateButton)
                    .addComponent(matchButton))
                .addGap(0, 27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void from4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_from4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_from4ActionPerformed

    private void from7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_from7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_from7ActionPerformed

    private void from8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_from8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_from8ActionPerformed

    private void to6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_to6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_to6ActionPerformed

    private void populateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_populateButtonActionPerformed
            ArrayList <Course> classArray = schedCheck.getSchedule(values.profid);
        // Loop through elements.
        //System.out.print(classArray);
        for (Course c : classArray){
            String place = c.getCourseLocation();
            String time = c.getCourseTime();
            String days = c.getCourseDays();
            String total = place+ " " + time + " " + days;
            
            if(from1.getText().isEmpty()){
                from1.setText(total);
            }else if(from2.getText().isEmpty()){
               from2.setText(total); 
            }else if(from3.getText().isEmpty()){
               from3.setText(total); 
            }else if(from4.getText().isEmpty()){
               from4.setText(total); 
            }else if(from5.getText().isEmpty()){
               from5.setText(total); 
            }else if(from6.getText().isEmpty()){
               from6.setText(total); 
            }else if(from7.getText().isEmpty()){
               from7.setText(total); 
            }else{
               from8.setText(total); 
            }
            
            if(to1.getText().isEmpty()){
                to1.setText(total);
            }else if(to2.getText().isEmpty()){
               to2.setText(total); 
            }else if(to3.getText().isEmpty()){
               to3.setText(total); 
            }else if(to4.getText().isEmpty()){
               to4.setText(total); 
            }else if(to5.getText().isEmpty()){
               to5.setText(total); 
            }else if(to6.getText().isEmpty()){
               to6.setText(total); 
            }else if(to7.getText().isEmpty()){
               to7.setText(total); 
            }else{
               to8.setText(total); 
            }            
            
        }
    }//GEN-LAST:event_populateButtonActionPerformed

    private void chooseFrom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFrom1ActionPerformed
        String selection = from1.getText();
        int end = selection.indexOf(" ");
        String courseName = selection.substring(0,end);
        String substr = selection.substring(end+1);
        int end2 = substr.indexOf(" ");
        String courseTime = selection.substring(end+1, end+end2+1);
        String courseDays = selection.substring(end+end2+2);
        
        int courseID = schedCheck.checkClass(courseName, courseTime, courseDays);
        values.classid = courseID;
        
        chooseFrom1.setBackground(Color.black);
    }//GEN-LAST:event_chooseFrom1ActionPerformed

    private void matchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matchButtonActionPerformed
        int classID = values.classid;
        int studentID = values.profid;
                
        ArrayList<Profile> matches = schedCheck.checkMatch(studentID, classID);
        for (Profile m : matches){
            String fname = m.getFirstName();
            String lname = m.getLastName();
            String phone = m.getPhoneNumber();
            String total = fname+ " " + lname + " " + phone;
            
            if(option1.getText().isEmpty()){
                option1.setText(total);
            }else if(option2.getText().isEmpty()){
               option2.setText(total); 
            }else if(option3.getText().isEmpty()){
               option3.setText(total); 
            }else{
               option4.setText(total); 
            }
        }
    }//GEN-LAST:event_matchButtonActionPerformed

    private void chooseFrom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFrom2ActionPerformed
        String selection = from2.getText();
        int end = selection.indexOf(" ");
        String courseName = selection.substring(0,end);
        String substr = selection.substring(end+1);
        int end2 = substr.indexOf(" ");
        String courseTime = selection.substring(end+1, end+end2+1);
        String courseDays = selection.substring(end+end2+2);
        
        int courseID = schedCheck.checkClass(courseName, courseTime, courseDays);
        values.classid = courseID;
        
        chooseFrom2.setBackground(Color.black);
    }//GEN-LAST:event_chooseFrom2ActionPerformed

    private void chooseFrom3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFrom3ActionPerformed
        String selection = from3.getText();
        int end = selection.indexOf(" ");
        String courseName = selection.substring(0,end);
        String substr = selection.substring(end+1);
        int end2 = substr.indexOf(" ");
        String courseTime = selection.substring(end+1, end+end2+1);
        String courseDays = selection.substring(end+end2+2);
        
        int courseID = schedCheck.checkClass(courseName, courseTime, courseDays);
        values.classid = courseID;
        
        chooseFrom3.setBackground(Color.black);
    }//GEN-LAST:event_chooseFrom3ActionPerformed

    private void chooseFrom5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFrom5ActionPerformed
        String selection = from5.getText();
        int end = selection.indexOf(" ");
        String courseName = selection.substring(0,end);
        String substr = selection.substring(end+1);
        int end2 = substr.indexOf(" ");
        String courseTime = selection.substring(end+1, end+end2+1);
        String courseDays = selection.substring(end+end2+2);
        
        int courseID = schedCheck.checkClass(courseName, courseTime, courseDays);
        values.classid = courseID;
        
        chooseFrom5.setBackground(Color.black);
    }//GEN-LAST:event_chooseFrom5ActionPerformed

    private void chooseFrom4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFrom4ActionPerformed
        String selection = from4.getText();
        int end = selection.indexOf(" ");
        String courseName = selection.substring(0,end);
        String substr = selection.substring(end+1);
        int end2 = substr.indexOf(" ");
        String courseTime = selection.substring(end+1, end+end2+1);
        String courseDays = selection.substring(end+end2+2);
        
        int courseID = schedCheck.checkClass(courseName, courseTime, courseDays);
        values.classid = courseID;
        
        chooseFrom4.setBackground(Color.black);
    }//GEN-LAST:event_chooseFrom4ActionPerformed

    private void chooseFrom6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFrom6ActionPerformed
        String selection = from6.getText();
        int end = selection.indexOf(" ");
        String courseName = selection.substring(0,end);
        String substr = selection.substring(end+1);
        int end2 = substr.indexOf(" ");
        String courseTime = selection.substring(end+1, end+end2+1);
        String courseDays = selection.substring(end+end2+2);
        
        int courseID = schedCheck.checkClass(courseName, courseTime, courseDays);
        values.classid = courseID;
        
        chooseFrom6.setBackground(Color.black);
    }//GEN-LAST:event_chooseFrom6ActionPerformed

    private void chooseFrom7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFrom7ActionPerformed
        String selection = from7.getText();
        int end = selection.indexOf(" ");
        String courseName = selection.substring(0,end);
        String substr = selection.substring(end+1);
        int end2 = substr.indexOf(" ");
        String courseTime = selection.substring(end+1, end+end2+1);
        String courseDays = selection.substring(end+end2+2);
        
        int courseID = schedCheck.checkClass(courseName, courseTime, courseDays);
        values.classid = courseID;
        
        chooseFrom7.setBackground(Color.black);
    }//GEN-LAST:event_chooseFrom7ActionPerformed

    private void chooseFrom8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFrom8ActionPerformed
        String selection = from8.getText();
        int end = selection.indexOf(" ");
        String courseName = selection.substring(0,end);
        String substr = selection.substring(end+1);
        int end2 = substr.indexOf(" ");
        String courseTime = selection.substring(end+1, end+end2+1);
        String courseDays = selection.substring(end+end2+2);
        
        int courseID = schedCheck.checkClass(courseName, courseTime, courseDays);
        values.classid = courseID;
        
        chooseFrom8.setBackground(Color.black);
    }//GEN-LAST:event_chooseFrom8ActionPerformed

    private void chooseTo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseTo1ActionPerformed
        chooseTo1.setBackground(Color.black);
    }//GEN-LAST:event_chooseTo1ActionPerformed

    private void chooseTo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseTo2ActionPerformed
        chooseTo2.setBackground(Color.black);
    }//GEN-LAST:event_chooseTo2ActionPerformed

    private void chooseTo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseTo3ActionPerformed
        chooseTo3.setBackground(Color.black);
    }//GEN-LAST:event_chooseTo3ActionPerformed

    private void chooseTo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseTo5ActionPerformed
        chooseTo5.setBackground(Color.black);
    }//GEN-LAST:event_chooseTo5ActionPerformed

    private void chooseTo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseTo4ActionPerformed
        chooseTo4.setBackground(Color.black);
    }//GEN-LAST:event_chooseTo4ActionPerformed

    private void chooseTo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseTo6ActionPerformed
        chooseTo6.setBackground(Color.black);
    }//GEN-LAST:event_chooseTo6ActionPerformed

    private void chooseTo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseTo7ActionPerformed
        chooseTo7.setBackground(Color.black);
    }//GEN-LAST:event_chooseTo7ActionPerformed

    private void chooseTo8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseTo8ActionPerformed
        chooseTo8.setBackground(Color.black);
    }//GEN-LAST:event_chooseTo8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseFrom1;
    private javax.swing.JButton chooseFrom2;
    private javax.swing.JButton chooseFrom3;
    private javax.swing.JButton chooseFrom4;
    private javax.swing.JButton chooseFrom5;
    private javax.swing.JButton chooseFrom6;
    private javax.swing.JButton chooseFrom7;
    private javax.swing.JButton chooseFrom8;
    private javax.swing.JButton chooseTo1;
    private javax.swing.JButton chooseTo2;
    private javax.swing.JButton chooseTo3;
    private javax.swing.JButton chooseTo4;
    private javax.swing.JButton chooseTo5;
    private javax.swing.JButton chooseTo6;
    private javax.swing.JButton chooseTo7;
    private javax.swing.JButton chooseTo8;
    private javax.swing.JTextField from1;
    private javax.swing.JTextField from2;
    private javax.swing.JTextField from3;
    private javax.swing.JTextField from4;
    private javax.swing.JTextField from5;
    private javax.swing.JTextField from6;
    private javax.swing.JTextField from7;
    private javax.swing.JTextField from8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton matchButton;
    private javax.swing.JTextField option1;
    private javax.swing.JTextField option2;
    private javax.swing.JTextField option3;
    private javax.swing.JTextField option4;
    private javax.swing.JButton populateButton;
    private javax.swing.JTextField to1;
    private javax.swing.JTextField to2;
    private javax.swing.JTextField to3;
    private javax.swing.JTextField to4;
    private javax.swing.JTextField to5;
    private javax.swing.JTextField to6;
    private javax.swing.JTextField to7;
    private javax.swing.JTextField to8;
    // End of variables declaration//GEN-END:variables
}
